### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by hackan88** [DSorlov/hasl-lovelace#2]
Några planer på att göra kortet kompatibelt med HACS? Skulle vara trevligt att ha både komponent och kort där.

**Comment by dimmanramone** [comment]
That's the plan. Already started with that but not totally done yet. Hopefully I'll have some time to get it done the following weeks.

**Comment by fredrikbaberg** [comment]
Looking forward to it!

**Comment by dimmanramone** [comment]
@hackan88 @fredrikbaberg HACS is now implemented but probably not live yet in the official HACS store. You can add the cards as custom HACS plugins by adding the following repos or wait a day until they show up in the HACS store.

https://github.com/hasl-platform/lovelace-hasl-departure-card

https://github.com/hasl-platform/lovelace-hasl-traffic-status-card
