### ISSUE TITLE
Card crash when there is no data

### ISSUE THREAD

**Issue by fredrikbaberg** [DSorlov/hasl-lovelace#3]
When using a boolean to limit updates of hasl-platform, I receive the following:
`https://<host>:8123/local/hasl-traffic-status-card.js:243:59 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined`

I noticed this when I restarted, with the sensor disabled, such that there is no data retrieved. Unfortunately it also crashes Lovelace for me, in the sense that I am no longer able to edit the UI of that specific tab.

**Comment by dimmanramone** [comment]
I'll look into it asap and try to reproduce it.

**Comment by fredrikbaberg** [comment]
I'm using Chrome on Windows 10 by the way. And I've had similar experience when I was working on my own card, so the issue that I cannot modify Lovelace is probably more of an issue with Lovelace and not the card itself.

But it is still good to see if it can be fixed.
