### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by MaxVonk** [DSorlov/hasl-lovelace#4]
Hi,

I've been trying to get this script to work but i keep getting 
`Custom element doesn't exist: hasl-departure-card.`

After some digging in the debug i found this:
`/local/hasl-departure-card.js:7:0 SyntaxError: expected expression, got '<'`

Any ideas?

**Comment by dimmanramone** [comment]
@MaxVonk Did you manage fix that? If not can you post your configuration.

**Comment by MaxVonk** [comment]
Hi,

I upgraded the HA installation, cant remember from what but i ended up with 0.99.3 and now it works as intended!
