### ISSUE TITLE
Entire lovelace view goes blank if max_departures exceed actual departures

### ISSUE THREAD

**Issue by tomoqv** [DSorlov/hasl-lovelace#5]
When adding `max_departures` to the config, the entire lovelace view, where the `hasl-card` is, goes blank if the number exceeds the actual departures from the SL-api feed. As soon as `max_departures` is commented out, the view (and the `hasl-card`) comes back.

**Comment by dimmanramone** [comment]
I'll try to reproduce and get back to you

**Comment by tomoqv** [comment]
Thanks!

**Comment by dimmanramone** [comment]
@tomoqv Pushed a fix for these in the dev branch, if you want to test it.
