### ISSUE TITLE
Add a “time_offset”

### ISSUE THREAD

**Issue by tomoqv** [DSorlov/hasl-lovelace#7]
Add a “time_offset” to take into account the amount of time it takes to reach the station, i.e. if it takes 8 minutes to walk to the train, only show departures from `now() + 8 minutes` onwards.

**Comment by dimmanramone** [comment]
Let me get back to you about that. Don't really see ther reason that something like that should be implemented and if it is something that should be on the card or the sensor.

**Comment by tomoqv** [comment]
The thing is, that I would like to conserve space in some of my Lovelace views. Showing a number of departures that are impossible to make from my house adds a few lines of information that is of little or no interest to the person looking for the next possible departure. This is a feature request, so I fully understand if it may be low priority.

**Comment by dimmanramone** [comment]
Ok now I get what exactly you want to do. I think this is better to be on the hasl sensor instead of the hasl card. What do you think @DSorlov ?

**Comment by dimmanramone** [comment]
Moved to https://github.com/hasl-platform/lovelace-hasl-departure-card/issues
