### ISSUE TITLE
More flexibility about elements to display

### ISSUE THREAD

**Issue by tomoqv** [DSorlov/hasl-lovelace#8]
I would like to hide, for instance, the header (to save space) and the end station (as some buses/trains/trams always end at the same station).

**Comment by dimmanramone** [comment]
Not really sure what do you want to do, there is already an option to hide the headers? Or do you want to hide the name of the card?

**Comment by tomoqv** [comment]
I would like to hide the name of the card and get that space compressed.
![hasl-card](https://user-images.githubusercontent.com/13762919/66750909-02211500-ee8e-11e9-8742-20aabd398023.png)

**Comment by hekm77** [comment]
@tomoqv 
You can remove line [173](https://github.com/DSorlov/hasl-cards/blob/54e627262d3cfff6d24ae1572e3c85e47aa50934/www/hasl-departure-card.js#L173 ) from _hasl-departure-card.js_

<img width="502" alt="111" src="https://user-images.githubusercontent.com/22895433/66751368-31845180-ee8f-11e9-8051-b7acad5e733e.png">

**Comment by dimmanramone** [comment]
@tomoqv Ok. I'll try to have that in the next release

**Comment by tomoqv** [comment]
Great, thanks a lot!

**Comment by dimmanramone** [comment]
@tomoqv Added new variable for hiding the card name. More than welcome to test this.
